import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Globe, Lock, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { chapterArt } from "@/lib/data/chapter-art";
import { getStats } from "@/lib/data/books";
import { getDictionary, hasLocale, localePath } from "@/lib/i18n";
import { formatCompactIn, formatNumberIn, textClass } from "@/lib/i18n/content";
import { site } from "@/lib/site";
import { cn } from "@/lib/utils";
import { fill } from "@/lib/i18n/format";

export async function generateMetadata(
  props: PageProps<"/[lang]/about">,
): Promise<Metadata> {
  const { lang } = await props.params;
  if (!hasLocale(lang)) return {};
  const dict = getDictionary(lang);

  return {
    title: dict.about.eyebrow,
    description: dict.about.metaDescription,
    alternates: {
      canonical: localePath(lang, "/about"),
      languages: {
        en: localePath("en", "/about"),
        bn: localePath("bn", "/about"),
      },
    },
  };
}

export default async function AboutPage(props: PageProps<"/[lang]/about">) {
  const { lang } = await props.params;
  if (!hasLocale(lang)) notFound();
  const dict = getDictionary(lang);

  const stats = await getStats();
  const propIcons = [Zap, Lock, Globe];

  return (
    <div className="mx-auto max-w-3xl px-5 py-14 lg:py-24">
      <p
        className={cn(
          "text-sm font-semibold uppercase tracking-[0.2em] text-accent",
          textClass(lang),
        )}
      >
        {dict.about.eyebrow}
      </p>
      <h1
        className={cn(
          "mt-2 text-[clamp(2.2rem,5.5vw,3.6rem)] font-bold tracking-tight text-ink",
          lang === "bn" ? "bn leading-[1.3]" : "leading-[1.08]",
        )}
      >
        {dict.about.title}
      </h1>

      <div
        className={cn(
          "reveal-3d mt-10 space-y-6 text-lg leading-relaxed text-ink-mute",
          textClass(lang),
        )}
      >
        <p>
          {fill(lang, dict.about.lead, {
            name: site.name,
            books: formatCompactIn(stats.totalBooks, lang),
          })}
        </p>
        <p>{dict.about.body}</p>
      </div>

      <div className="mt-14 grid gap-6 sm:grid-cols-3">
        {dict.about.props.map((prop, i) => {
          const Icon = propIcons[i];
          return (
            <div
              key={prop.title}
              className="reveal-3d"
              style={{ "--lag": i * 5 } as React.CSSProperties}
            >
              <span className="inline-flex size-11 items-center justify-center rounded-xl bg-accent-soft text-accent">
                <Icon className="size-5" aria-hidden="true" />
              </span>
              <h2 className={cn("mt-4 font-semibold text-ink", textClass(lang))}>
                {prop.title}
              </h2>
              <p
                className={cn(
                  "mt-2 text-[0.95rem] leading-relaxed text-ink-mute",
                  textClass(lang),
                )}
              >
                {prop.body}
              </p>
            </div>
          );
        })}
      </div>

      <dl className="reveal-3d mt-16 grid grid-cols-2 gap-8 rounded-2xl border border-line bg-surface p-8 sm:grid-cols-4">
        {[
          {
            label: dict.about.statBooks,
            value: formatCompactIn(stats.totalBooks, lang),
          },
          {
            label: dict.about.statAuthors,
            value: formatCompactIn(stats.totalAuthors, lang),
          },
          {
            label: dict.about.statCategories,
            value: formatNumberIn(stats.totalCategories, lang),
          },
          {
            label: dict.about.statDownloads,
            value: formatCompactIn(stats.totalDownloads, lang),
          },
        ].map((s) => (
          <div key={s.label}>
            <dt className={cn("text-sm text-ink-faint", textClass(lang))}>
              {s.label}
            </dt>
            <dd className="mt-1 text-3xl font-bold tracking-tight text-ink">
              {s.value}
            </dd>
          </div>
        ))}
      </dl>

      {/* The picture credits.
          Not a courtesy. Every plate behind a chapter heading on this site is
          somebody else's work under a Creative Commons licence, and most of
          them are share-alike, which makes attribution a condition of using
          them at all. `chapter-art.ts` is generated by the build script from
          what Commons returned, so a plate cannot reach the site without its
          credit arriving with it — but that was only true of the data until
          now: the module was generated, and then nothing rendered it. This is
          the half that was missing. */}
      <section className="reveal mt-20 border-t border-line-soft pt-10">
        <h2 className={cn("text-sm font-semibold text-ink", textClass(lang))}>
          {dict.about.creditsTitle}
        </h2>
        <p className={cn("mt-2 max-w-2xl text-sm text-ink-mute", textClass(lang))}>
          {dict.about.creditsLead}
        </p>
        <ul className="mt-6 grid gap-x-10 gap-y-3 sm:grid-cols-2">
          {chapterArt.map((art) => (
            <li key={art.slug} className="text-sm leading-relaxed">
              <a
                href={art.sourceUrl}
                className="text-ink underline decoration-line underline-offset-4 hover:decoration-accent"
                rel="noreferrer"
              >
                {art.title}
              </a>
              <span className="text-ink-faint">
                {" — "}
                {art.artist}
                {", "}
                {art.license}
              </span>
            </li>
          ))}
        </ul>
      </section>

      <div className="reveal-3d mt-14">
        <Button asChild size="lg" variant="primary">
          <Link href={localePath(lang, "/books")}>
            {dict.common.startBrowsing}
            <ArrowRight className="size-4" aria-hidden="true" />
          </Link>
        </Button>
      </div>
    </div>
  );
}
