/**
 * Credits for the chapter backgrounds.
 *
 * Generated by `scripts/build-chapter-art.mjs`; do not hand-edit. These are
 * other people's photographs under Creative Commons, and attribution is a
 * condition of those licences rather than a courtesy, so the credits are a
 * module the About page imports, which means a photograph cannot reach the site
 * without one.
 */

export interface ChapterArt {
  /** Category slug: the join to `public/bg/<slug>.webp`. */
  slug: string;
  title: string;
  artist: string;
  license: string;
  sourceUrl: string;
}

export const chapterArt: readonly ChapterArt[] = [
  {
    slug: "bedside-reference",
    title: "Mesentery extending from the duodenojejunal flexure to the ileocecal junction.",
    artist: "https://www.scientificanimations.com/",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mesentery_extending_from_the_duodenojejunal_flexure_to_the_ileocecal_junction..jpg"
  },
  {
    slug: "exam-revision",
    title: "Salivary Gland",
    artist: "http://www.scientificanimations.com/",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Salivary_Gland.jpg"
  },
  {
    slug: "reflux-upper-gut",
    title: "3D Medical Animation Stomach Structure",
    artist: "https://www.scientificanimations.com",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:3D_Medical_Animation_Stomach_Structure.jpg"
  },
  {
    slug: "liver-bile-pancreas",
    title: "Gallbladder stones",
    artist: "www.scientificanimations.com",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gallbladder_stones.jpg"
  },
  {
    slug: "endoscopy-imaging",
    title: "Irritable bowel syndrome",
    artist: "http://www.scientificanimations.com",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Irritable_bowel_syndrome.jpg"
  },
  {
    slug: "gut-cancer",
    title: "3D Medical Animation Acute Pancreatitis",
    artist: "https://www.scientificanimations.com",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:3D_Medical_Animation_Acute_Pancreatitis.jpg"
  },
  {
    slug: "children-digestive-health",
    title: "Inflammed mucous layer of the intestinal villi depicting Celiac disease",
    artist: "www.scientificanimations.com",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Inflammed_mucous_layer_of_the_intestinal_villi_depicting_Celiac_disease.jpg"
  }
];

export function artFor(slug: string): ChapterArt | undefined {
  return chapterArt.find((art) => art.slug === slug);
}
